package com.catsitter.api.entity.enums;

public enum ActionType {
  ORDER_CREATED,
  STATUS_CHANGED,
  QUESTIONNAIRE_SENT,
  VISIT_STARTED,
  VISIT_COMPLETED,
  TASK_COMPLETED,
  TRANSFER_REQUESTED,
  ORDER_CANCELLED,
  ORDER_COMPLETED
}
