debug: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cat_sitter_db
    username: sitter_admin
    password: dev_password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # 既然用了 Flyway，就關閉 Hibernate 的自動建表，全權交給 Flyway 處理
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

application:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 3600000 # 1 hour
    refresh-token:
      expiration: 604800000 # 7 days

server:
  port: 8081